name: net security workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ## Sets environment variable
  PUBLICENV: Available for all jobs in this workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      # - name: Test with Gradle
      #   run: ./gradlew clean build
      - name: update ubuntu
        run: sudo apt-get update
      - name: install groovy
        run: sudo apt-get install groovy
      - name: execute groovy sample script
        run: groovy .github/workflows/scripts/sample.groovy
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying Action $PUBLICENV runId $GITHUB_RUN_ID"
